"""
daily_notes.py — Generate daily memory files (memory/YYYY-MM-DD.md).

Extracted from the daily notes pattern in Mordechai's memory/ directory.
Each daily note captures: topics discussed, decisions made, tasks started/completed,
mood/energy, and key quotes.

This runs nightly (e.g., 23:00) and creates a structured summary of the day's
session activity.
"""

from __future__ import annotations

import json
import os
from datetime import datetime, timedelta
from pathlib import Path
from typing import Optional

from .context_windows import (
    extract_decisions,
    extract_topics,
    extract_user_messages,
    find_recent_sessions,
    detect_mode,
    STOP_WORDS,
)


DAILY_TEMPLATE = """# {date} — Daily Memory

**Generated:** {generated_at}
**Sessions:** {session_count} | **Messages:** {message_count} | **Mode:** {mode}

## Topics Discussed

{topics_section}

## Decisions Made

{decisions_section}

## Tasks Started/Completed

{tasks_section}

## Key Observations

{observations}

---
*Auto-generated by agent-memory-loop. Edit freely — this is your memory.*
"""


def generate_daily_note(
    sessions_dir: str | Path,
    output_dir: str | Path,
    date: datetime | None = None,
    window_minutes: int = 1440,
) -> Path | None:
    """
    Generate a daily memory file for the given date.

    Args:
        sessions_dir: Path to JSONL session files.
        output_dir: Path to memory/ directory.
        date: Date to generate for (default: today).
        window_minutes: How far back to scan (default: 24h = 1440 min).

    Returns:
        Path to the generated file, or None if no activity.
    """
    sessions_dir = Path(sessions_dir)
    output_dir = Path(output_dir)
    if date is None:
        date = datetime.now()

    date_str = date.strftime("%Y-%m-%d")
    output_path = output_dir / f"{date_str}.md"

    # Find sessions active today
    sessions = find_recent_sessions(sessions_dir, window_minutes)
    if not sessions:
        return None

    # Extract all messages
    all_messages: list[str] = []
    for sf in sessions:
        all_messages.extend(extract_user_messages(sf))

    if not all_messages:
        return None

    # Analyze
    topics = extract_topics(all_messages, max_words=15)
    decisions = extract_decisions(all_messages, max_decisions=10)
    mode = detect_mode(all_messages)

    # Format topics
    if topics:
        topics_section = "\n".join(
            f"- **{word}** — mentioned {count} times" for word, count in topics
        )
    else:
        topics_section = "_No notable topics detected._"

    # Format decisions
    if decisions:
        decisions_section = "\n".join(f"- {d}" for d in decisions)
    else:
        decisions_section = "_No explicit decisions captured._"

    # Tasks section (placeholder — real implementation would cross-reference STATE.json)
    tasks_section = (
        "_Cross-reference with STATE.json for task updates._\n"
        f"_Activity across {len(sessions)} sessions suggests {mode} mode._"
    )

    # Observations
    observations = _generate_observations(
        session_count=len(sessions),
        message_count=len(all_messages),
        mode=mode,
        topics=topics,
    )

    # Write
    content = DAILY_TEMPLATE.format(
        date=date_str,
        generated_at=datetime.now().strftime("%Y-%m-%d %H:%M %Z"),
        session_count=len(sessions),
        message_count=len(all_messages),
        mode=mode,
        topics_section=topics_section,
        decisions_section=decisions_section,
        tasks_section=tasks_section,
        observations=observations,
    )

    output_dir.mkdir(parents=True, exist_ok=True)

    # Don't overwrite existing human-edited notes
    if output_path.exists():
        # Append a machine-generated section
        existing = output_path.read_text()
        if "Auto-generated by agent-memory-loop" not in existing:
            content = (
                existing.rstrip()
                + "\n\n---\n\n## 🤖 Auto-Generated Summary\n\n"
                + content
            )
            output_path.write_text(content)
        # If already has auto-generated section, skip
        return output_path

    output_path.write_text(content)
    return output_path


def _generate_observations(
    session_count: int,
    message_count: int,
    mode: str,
    topics: list[tuple[str, int]],
) -> str:
    """Generate brief observations about the day's activity."""
    observations = []

    if session_count > 10:
        observations.append(
            f"High session count ({session_count}) — scattered attention or many quick tasks."
        )
    elif session_count <= 2:
        observations.append(
            f"Low session count ({session_count}) — focused deep work or light day."
        )

    if message_count > 200:
        observations.append("Heavy interaction day — lots of back-and-forth.")
    elif message_count < 20:
        observations.append("Quiet day — minimal interaction.")

    if "debugging" in mode:
        observations.append("Debugging mode detected — troubleshooting session.")
    elif "building" in mode:
        observations.append("Building mode — productive construction work.")
    elif "exploring" in mode:
        observations.append("Exploration mode — research and deep dives.")

    if topics and topics[0][1] > 20:
        observations.append(
            f"Strong topic focus on **{topics[0][0]}** ({topics[0][1]}x mentions)."
        )

    return "\n".join(f"- {o}" for o in observations) if observations else "_Normal day._"
